In [11]:
from pathlib import Path
import pandas as pd

csv_path = Path("/Users/sparrkie/faf-secure-logistics-analysis/data/raw/extracted/FAF5.7.1.csv")
df = pd.read_csv(csv_path)

df.head()

,fr_orig,dms_orig,dms_dest,fr_dest,fr_inmode,dms_mode,fr_outmode,sctg2,trade_type,dist_band,...,tmiles_2020,tmiles_2021,tmiles_2022,tmiles_2023,tmiles_2024,tmiles_2030,tmiles_2035,tmiles_2040,tmiles_2045,tmiles_2050
0,NaN,11,11,NaN,NaN,1,NaN,1,1,1,...,3.375547,3.482383,3.502040,3.469055,3.474500,5.327137,6.342501,7.763605,9.571647,11.343818
1,NaN,11,19,NaN,NaN,1,NaN,1,1,2,...,51.005589,52.619906,52.916934,52.418516,52.500796,72.493059,82.113979,96.869428,116.602924,134.683927
2,NaN,11,129,NaN,NaN,1,NaN,1,1,3,...,0.472040,0.486980,0.489729,0.485116,0.485878,0.533539,0.564126,0.638719,0.750361,0.844720
3,NaN,11,131,NaN,NaN,1,NaN,1,1,2,...,2.283328,2.355595,2.368892,2.346580,2.350263,3.018065,3.155784,3.394250,3.850035,4.178881
4,NaN,11,139,NaN,NaN,1,NaN,1,1,2,...,1.337213,1.379536,1.387323,1.374256,1.376413,1.863748,1.969298,2.141527,2.456208,2.683008

In [12]:
df.columns.tolist()

['fr_orig',
 'dms_orig',
 'dms_dest',
 'fr_dest',
 'fr_inmode',
 'dms_mode',
 'fr_outmode',
 'sctg2',
 'trade_type',
 'dist_band',
 'tons_2017',
 'tons_2018',
 'tons_2019',
 'tons_2020',
 'tons_2021',
 'tons_2022',
 'tons_2023',
 'tons_2024',
 'tons_2030',
 'tons_2035',
 'tons_2040',
 'tons_2045',
 'tons_2050',
 'value_2017',
 'value_2018',
 'value_2019',
 'value_2020',
 'value_2021',
 'value_2022',
 'value_2023',
 'value_2024',
 'value_2030',
 'value_2035',
 'value_2040',
 'value_2045',
 'value_2050',
 'current_value_2018',
 'current_value_2019',
 'current_value_2020',
 'current_value_2021',
 'current_value_2022',
 'current_value_2023',
 'current_value_2024',
 'tmiles_2017',
 'tmiles_2018',
 'tmiles_2019',
 'tmiles_2020',
 'tmiles_2021',
 'tmiles_2022',
 'tmiles_2023',
 'tmiles_2024',
 'tmiles_2030',
 'tmiles_2035',
 'tmiles_2040',
 'tmiles_2045',
 'tmiles_2050']

In [13]:
[col for col in df.columns if "tmiles" in col]

['tmiles_2017',
 'tmiles_2018',
 'tmiles_2019',
 'tmiles_2020',
 'tmiles_2021',
 'tmiles_2022',
 'tmiles_2023',
 'tmiles_2024',
 'tmiles_2030',
 'tmiles_2035',
 'tmiles_2040',
 'tmiles_2045',
 'tmiles_2050']

In [14]:
# Create smaller working dataframe

id_cols = ["dms_orig", "dms_dest", "dms_mode", "sctg2", "trade_type", "dist_band"]

tons_cols = [f"tons_{year}" for year in range(2018, 2025)]
value_cols = [f"value_{year}" for year in range(2018, 2025)]
tmiles_cols = [f"tmiles_{year}" for year in range(2018, 2025)]

keep_cols = id_cols + tons_cols + value_cols + tmiles_cols

faf = df[keep_cols].copy()

faf.head()

,dms_orig,dms_dest,dms_mode,sctg2,trade_type,dist_band,tons_2018,tons_2019,tons_2020,tons_2021,...,value_2022,value_2023,value_2024,tmiles_2018,tmiles_2019,tmiles_2020,tmiles_2021,tmiles_2022,tmiles_2023,tmiles_2024
0,11,11,1,1,1,1,51.863434,54.012407,54.395645,56.117256,...,74.639408,73.936389,74.052445,3.218410,3.351765,3.375547,3.482383,3.502040,3.469055,3.474500
1,11,19,1,1,1,2,392.072310,408.317910,411.215079,424.229954,...,564.251994,558.937374,559.814725,48.631191,50.646235,51.005589,52.619906,52.916934,52.418516,52.500796
2,11,129,1,1,1,3,1.383202,1.440515,1.450736,1.496652,...,1.990640,1.971890,1.974985,0.450066,0.468714,0.472040,0.486980,0.489729,0.485116,0.485878
3,11,131,1,1,1,2,12.698528,13.224694,13.318528,13.740057,...,18.275123,18.102991,18.131407,2.177036,2.267241,2.283328,2.355595,2.368892,2.346580,2.350263
4,11,139,1,1,1,2,5.220302,5.436606,5.475181,5.648469,...,7.512813,7.442051,7.453732,1.274964,1.327792,1.337213,1.379536,1.387323,1.374256,1.376413

In [15]:
tons_col = [col for col in df.columns if "tons" in col]
val_col = [col for col in df.columns if "value" in col]
print(tons_col)
print(val_col)

['tons_2017', 'tons_2018', 'tons_2019', 'tons_2020', 'tons_2021', 'tons_2022', 'tons_2023', 'tons_2024', 'tons_2030', 'tons_2035', 'tons_2040', 'tons_2045', 'tons_2050']
['value_2017', 'value_2018', 'value_2019', 'value_2020', 'value_2021', 'value_2022', 'value_2023', 'value_2024', 'value_2030', 'value_2035', 'value_2040', 'value_2045', 'value_2050', 'current_value_2018', 'current_value_2019', 'current_value_2020', 'current_value_2021', 'current_value_2022', 'current_value_2023', 'current_value_2024']

In [16]:
id_cols = ["dms_orig", "dms_dest", "dms_mode", "sctg2", "trade_type", "dist_band"]

records = []

for year in range(2018, 2025):
    temp = faf[id_cols].copy()
    temp["year"] = year
    temp["tons"] = faf[f"tons_{year}"]
    temp["value"] = faf[f"value_{year}"]
    temp["tmiles"] = faf[f"tmiles_{year}"]
    records.append(temp)

faf_long = pd.concat(records, ignore_index=True)

In [21]:
faf_long.head()
faf_long.info()

<class 'pandas.DataFrame'>
RangeIndex: 18699702 entries, 0 to 18699701
Data columns (total 10 columns):
 #   Column      Dtype
---  ------      -----
 0   dms_orig    int32
 1   dms_dest    int32
 2   dms_mode    int8
 3   sctg2       int8
 4   trade_type  int8
 5   dist_band   int8
 6   year        int16
 7   tons        float32
 8   value       float32
 9   tmiles      float32
dtypes: float32(3), int16(1), int32(2), int8(4)
memory usage: 463.7 MB

In [19]:
faf_long.to_csv("../data/processed/faf_long_2018_2024.csv", index=False)

KeyboardInterrupt:

In [20]:
faf_long["dms_orig"] = faf_long["dms_orig"].astype("int32")
faf_long["dms_dest"] = faf_long["dms_dest"].astype("int32")
faf_long["dms_mode"] = faf_long["dms_mode"].astype("int8")
faf_long["sctg2"] = faf_long["sctg2"].astype("int8")
faf_long["trade_type"] = faf_long["trade_type"].astype("int8")
faf_long["dist_band"] = faf_long["dist_band"].astype("int8")
faf_long["year"] = faf_long["year"].astype("int16")

faf_long["tons"] = faf_long["tons"].astype("float32")
faf_long["value"] = faf_long["value"].astype("float32")
faf_long["tmiles"] = faf_long["tmiles"].astype("float32")